Adding updated config.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,20 +19,21 @@ jobs:
             key: source-cache-connectivity
             paths:
               - ".git"
-        # - run:
-        #     name: Set BASH_ENV
-        #     command: |
-        #       set -e
-        #       echo "set -e" >> $BASH_ENV
-        #       echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
-        #       echo "export XDG_RUNTIME_DIR=/tmp/runtime-circleci" >> $BASH_ENV
-        #       wget -q -O tools/get_minimal_commands.sh https://raw.githubusercontent.com/mne-tools/mne-python/main/tools/get_minimal_commands.sh
-        #       source tools/get_minimal_commands.sh
-        #       echo "source ${PWD}/tools/get_minimal_commands.sh" >> $BASH_ENV
-        #       echo "export PATH=~/.local/bin/:$PATH" >> $BASH_ENV
-        #       echo "BASH_ENV:"
-        #       cat $BASH_ENV
-        #       mkdir -p ~/mne_data
+        - run:
+            name: Set BASH_ENV
+            command: |
+              set -e
+              echo "set -e" >> $BASH_ENV
+              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
+              echo "export XDG_RUNTIME_DIR=/tmp/runtime-circleci" >> $BASH_ENV
+              echo "export MNE_FULL_DATE=true" >> $BASH_ENV
+              source tools/get_minimal_commands.sh
+              echo "export MNE_3D_BACKEND=pyvista" >> $BASH_ENV
+              echo "export PATH=~/.local/bin/:$PATH" >> $BASH_ENV
+              echo "BASH_ENV:"
+              cat $BASH_ENV
+              mkdir -p ~/mne_data
+              touch pattern.txt;
 
         - run:
             name: Merge with upstream
@@ -47,19 +48,23 @@ jobs:
         - restore_cache:
             keys:
               - pip-cache
-
+        - restore_cache:
+            keys:
+              - user-install-bin-cache
         - run:
             name: Get Python running
             command: |
-              pip install --user --upgrade --progress-bar off pip numpy
-              pip install --user --upgrade --progress-bar off -r requirements.txt
-              pip install --user --upgrade --progress-bar off -r test_requirements.txt
-              pip install --user --upgrade --progress-bar off "https://api.github.com/repos/mne-tools/mne-python/zipball/main"
-
+              ./tools/circleci_dependencies.sh
         - save_cache:
             key: pip-cache
             paths:
               - ~/.cache/pip
+
+        - save_cache:
+            key: user-install-bin-cache
+            paths:
+              - ~/.local/lib/python3.8/site-packages
+              - ~/.local/bin
 
         # Look at what we have and fail early if there is some library conflict
         - run:
@@ -75,6 +80,27 @@ jobs:
         - restore_cache:
             keys:
               - data-cache
+        
+        - run:
+            name: Check PyQt5
+            command: LD_DEBUG=libs python -c "from PyQt5.QtWidgets import QApplication, QWidget; app = QApplication([])"
+
+        # Load tiny cache so that ~/.mne does not need to be created below
+        - restore_cache:
+            keys:
+              - data-cache-tiny-0
+
+        # Look at what we have and fail early if there is some library conflict
+        - run:
+            name: Check installation
+            command: |
+               which python
+               QT_DEBUG_PLUGINS=1 mne sys_info
+               python -c "import numpy; numpy.show_config()"
+               LIBGL_DEBUG=verbose python -c "import pyvistaqt; pyvistaqt.BackgroundPlotter(show=True)"
+               python -c "import mne; mne.set_config('MNE_USE_CUDA', 'false')"  # this is needed for the config tutorial
+               python -c "import mne; mne.set_config('MNE_LOGGING_LEVEL', 'info')"
+               python -c "import mne; level = mne.get_config('MNE_LOGGING_LEVEL'); assert level.lower() == 'info', repr(level)"
 
         - run:
             name: Get data
